ALTER TABLE VSTG_ETL_OWNER.P3_VACCINES_STG_VAC_PODS ADD CAND_CODE NVARCHAR2(6);
ALTER TABLE VSTG_ETL_OWNER.P3_VACCINES_STG_VAC_PODS ADD CAND_MEDIUM_DESC NVARCHAR2(35);

ALTER TABLE VSTG_SYNC_OWNER.P3_VACCINES_VS_VAC_PODS ADD CAND_CODE NVARCHAR2(6);
ALTER TABLE VSTG_SYNC_OWNER.P3_VACCINES_VS_VAC_PODS ADD CAND_MEDIUM_DESC NVARCHAR2(35);