--If any failure and error occurred then script rolls back exists--
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
WHENEVER OSERROR EXIT FAILURE ROLLBACK
--log file is specified for spooling--
SPOOL backup.log

--USERID, DB name and timestamp spooling in log--

SELECT 'User                      :   ', USER FROM DUAL;

SELECT 'Global Name               :   ', GLOBAL_NAME FROM GLOBAL_NAME;

SELECT 'System Date               :   ',
       TO_CHAR (SYSDATE, 'DD-MON-YYYY HH24:MM:DD')
  FROM DUAL;

-- Set Echo ON so that each commend executed should be available in LOG--
SET ECHO ON



CREATE TABLE KOL_IB_OWNER.POL_M2M_INTRM_LANDING_TABLE_bkp170622 as SELECT * FROM KOL_IB_OWNER.POL_M2M_INTRM_LANDING_TABLE;
CREATE TABLE KOL_IB_OWNER.POL_M2M_LANDING_TABLE_bkp170622 as SELECT * FROM KOL_IB_OWNER.POL_M2M_LANDING_TABLE;
CREATE TABLE KOL_IB_OWNER.POL_INTRM_LND_ENGAGE2_bkp170622 as SELECT * FROM KOL_IB_OWNER.POL_INTRM_LND_ENGAGE2;
CREATE TABLE KOL_IB_OWNER.POL_LND_ENGAGE_bkp170622 as SELECT * FROM KOL_IB_OWNER.POL_LND_ENGAGE; 

--
--KOL_STG_SYNC_OWNER
--

CREATE TABLE KOL_STG_SYNC_OWNER.POL_M2M_STAGING_TABLE_bkp170622 as SELECT * FROM KOL_STG_SYNC_OWNER.POL_M2M_STAGING_TABLE;
CREATE TABLE KOL_STG_SYNC_OWNER.POL_M2M_SFDC_SYNC_TABLE_bkp170622 as SELECT * FROM KOL_STG_SYNC_OWNER.POL_M2M_SFDC_SYNC_TABLE;
CREATE TABLE KOL_STG_SYNC_OWNER.POL_STG_INTRCTN_CALLS_bkp170622 as SELECT * FROM KOL_STG_SYNC_OWNER.POL_STG_INTRCTN_CALLS;

--
--KETL_CONTROL_OWNER
--

CREATE TABLE KETL_CONTROL_OWNER.POL_LND_ENGAGE_ERR_bkp170622 as SELECT * FROM KETL_CONTROL_OWNER.POL_LND_ENGAGE_ERR;
CREATE TABLE KETL_CONTROL_OWNER.POL_STG_INTRCTN_CALLS_ERR_bkp170622 as SELECT * FROM KETL_CONTROL_OWNER.POL_STG_INTRCTN_CALLS_ERR;
CREATE TABLE KETL_CONTROL_OWNER.PFORCERX_PFORCEOL_ACCOUNT_XREF_bkp170622 as SELECT * FROM KETL_CONTROL_OWNER.PFORCERX_PFORCEOL_ACCOUNT_XREF;
