DROP TABLE VSTG_SYNC_OWNER.P3_VACCINES_VS_VAC_PODS CASCADE CONSTRAINTS;

-----------------P3_VACCINES_VS_VAC_PODS
CREATE TABLE VSTG_SYNC_OWNER.P3_VACCINES_VS_VAC_PODS
(
  UNIQUE_ROW_ID       NUMBER,
  BATCH_ID            NUMBER,
  PROTOCOL_ID         NVARCHAR2(25),
  STUDY_TITLE         NCLOB,
  ACTUAL_CSR          DATE,
  ACTUAL_FSFV         DATE,
  ACTUAL_LSLV         DATE,
  NUMBER_OF_SITES     NUMBER,
  PLANNED_CSR         DATE,
  PLANNED_FSFV        DATE,
  PLANNED_LSLV        DATE,
  SFDC_ID             NVARCHAR2(18),
  ERROR_FLAG          NVARCHAR2(1),
  CHANGE_FLAG         NVARCHAR2(1),
  CAND_CODE           NVARCHAR2(6),
  CAND_MEDIUM_DESC    NVARCHAR2(35),
  CREATED_DATE        DATE,
  CREATED_BY          NVARCHAR2(50),
  LAST_MODIFIED_DATE  DATE,
  LAST_MODIFIED_BY    NVARCHAR2(50)  
)
LOB (STUDY_TITLE) STORE AS SECUREFILE (
  TABLESPACE  VSTG_REPL_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ));